### ISSUE TITLE
Error: "INFORMATION: Warning: there is no new image." No saving of the new images

### ISSUE THREAD

**Issue by JensWendt** [GReD-Clermont/omero_batch-plugin#11]
Hello,

I was made aware of this script by Pierre Pouchin in the recent OMERO admin meeting.
I love the functionality and the GUI.
But unfortunately I am getting an error while trying to process a small dataset and saving it both to local or OMERO.
```
Mär 28, 2022 12:40:59 PM fr.igred.ij.macro.OMEROBatchRunner save
INFORMATION: Warning: there is no new image.
```
The log does not display any more information.
Do you have any ideas on what might be the cause?
Additional info: 
I downloaded the latest OMERO plugin for Fiji (5.7.0) and our server runs on 5.6.3.
I do not think that the version discrepancy between plugin and server plays a role, as the exact same error occurs while trying to save the images locally.

Best regards

Jens

**Comment by ppouchin** [comment]
Hello, 


Sorry to come back to you this late: I did not receive any notification from Github, and so your issue went unnoticed.

This message normally indicates that the macro does not produce a new image, but only works on the original one. 
To clarify, the batch plugin only saves **images that remain open in ImageJ** at the end of the macro.

To prevent re-importing the original image each time, we skip the image that was opened from OMERO in the first place, otherwise users could quickly fill the server with duplicates.
(Maybe I should look if ImageJ provides a way to check whether the image has been modified or not, but I doubt it is possible.)

One way to circumvent this is to duplicate the original image in the macro, if it is possible:
`run("Duplicate...", "title=result duplicate");`

However, I might misinterpret the cause of the problem. How does your macro work? Are the new images left open, or are they saved on disk?

**Comment by JensWendt** [comment]
Hello Pierre,

You were spot on. 
I just had a small test macro running two filters over the image, basically just modifiying the original image.
I did not read the line "Only new images will be saved..." from the readme.md with the meaning you explained.
Thank you.
